"""Test writer: Generate pytest test code targeting branch coverage via AI."""

import os
from typing import List
from test_generator.code_analyzer import ClassAnalysis, MethodAnalysis

# Import the new AI agent loop we built
from test_generator.ai_agent import generate_passing_test


class TestWriter:
    """Generate structural tests targeting control flow branches using an LLM."""
    
    def __init__(self, class_analysis: ClassAnalysis, num_tests: int | None = None):
        """
        Initialize test writer.
        
        Args:
            class_analysis: ClassAnalysis object from code analyzer
            num_tests: Number of tests to generate.
        """
        self.class_analysis = class_analysis
        self.num_tests = num_tests or self._calculate_test_count()
        self.tested_methods: set[str] = set()
        
        # Define the temporary sandbox file the AI will use to verify its tests
        self.temp_test_file = "tests/test_structural_quoridor.py"
    
    def _calculate_test_count(self) -> int:
        """Calculate number of tests based on branches."""
        branch_count = self.class_analysis.total_branches
        return max(8, int(branch_count / 10))
    
    def get_tested_methods(self) -> set[str]:
        """Return set of method names that have tests."""
        return self.tested_methods
    
    def generate_test_file(self) -> str:
        """Generate complete pytest test file."""
        # 1. Setup the testing sandbox for the AI Agent
        self._setup_ai_sandbox()

        # 2. Build the final output string
        lines = []
        lines.extend(self._generate_header())
        lines.append("")
        lines.extend(self._generate_helpers())
        lines.append("")
        lines.extend(self._generate_fixtures())
        lines.append("")
        lines.append(self._generate_test_class())
        
        # 3. Clean up the sandbox after generation is complete
        if os.path.exists(self.temp_test_file):
            os.remove(self.temp_test_file)
            
        return "\n".join(lines)

    def _setup_ai_sandbox(self):
        """
        Create a temporary file with all fixtures and imports. 
        The AI agent needs this file to run `pytest` and verify its code.
        """
        os.makedirs(os.path.dirname(self.temp_test_file), exist_ok=True)
        base_code = "\n".join(
            self._generate_header() + 
            [""] + 
            self._generate_helpers() + 
            [""] + 
            self._generate_fixtures() + 
            ["", "class TestSandbox:", "    pass"]
        )
        with open(self.temp_test_file, 'w', encoding='utf-8') as f:
            f.write(base_code)
    
    def _generate_header(self) -> List[str]:
        """Generate file header."""
        return [
            "\"\"\"Auto-generated structural tests for Quoridor.",
            "",
            "This test module was automatically generated by the AI structural test agent.",
            "It targets branch/path coverage of the QuoridorEnv class.",
            "\"\"\"",
            "import os",
            "import sys",
            "import pytest",
            "from unittest.mock import MagicMock, patch",
            "",
            "sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))",
            "",
            "from Quoridor_Class import ACTION_H_BASE, ACTION_V_BASE, BOARD_SIZE, QuoridorEnv",
        ]
    
    def _generate_helpers(self) -> List[str]:
        """Generate helper functions."""
        return [
            "WALL_GRID_SIZE = BOARD_SIZE - 1",
            "",
            "def h_action(wr, wc):",
            "    return ACTION_H_BASE + wr * WALL_GRID_SIZE + wc",
            "",
            "def v_action(wr, wc):",
            "    return ACTION_V_BASE + wr * WALL_GRID_SIZE + wc",
            "",
            "def reset_walls(env):",
            "    env.walls_h[:, :] = 0",
            "    env.walls_v[:, :] = 0",
            "    env.walls_h_owner[:, :] = -1",
            "    env.walls_v_owner[:, :] = -1",
            "    env._path_cache.clear()",
            "    env._walls_sig_dirty = True",
        ]
    
    def _generate_fixtures(self) -> List[str]:
        """Generate pytest fixtures."""
        return [
            "@pytest.fixture",
            "def env():",
            "    environment = QuoridorEnv()",
            "    environment.reset()",
            "    return environment",
        ]
    
    def _generate_test_class(self) -> str:
        """Generate test class with branch-targeting tests."""
        lines = [
            "class TestStructuralCoverage:",
            '    """Structural tests targeting branch coverage.',
            "",
            f"    Tests {self.num_tests} critical code paths exercising:",
            "    - IF statement branches (TRUE vs FALSE)",
            "    - Loop iterations and termination conditions",
            "    \"\"\"",
            "",
        ]
        
        # Get methods sorted by branch count
        methods = sorted(
            [m for m in self.class_analysis.methods.values() if m.total_branches > 0],
            key=lambda m: (-m.total_branches, m.method_name)
        )
        
        test_count = 0
        for method in methods:
            if test_count >= self.num_tests:
                break
            
            # Delegate to AI Agent to write the tests for this method
            test_code = self._generate_branch_tests_via_ai(method)
            if test_code:
                lines.append(test_code)
                lines.append("")
                self.tested_methods.add(method.method_name)
                test_count += 1
        
        return "\n".join(lines)
    
    def _generate_branch_tests_via_ai(self, method: MethodAnalysis) -> str:
        """Extract method source and dispatch the AI Agent to write branch tests."""
        # Clean up method name for test function naming
        safe_name = method.method_name.replace('_', 'x_')
        
        # Extract the exact source code of the method to give the LLM context
        start_idx = method.line_start - 1
        end_idx = method.line_end
        method_source = "\n".join(self.class_analysis.source_lines[start_idx:end_idx])
        
        generated_tests = []
        
        for branch in method.if_statements:
            test_name = f"test_{safe_name}_branch_line_{branch.line_num}"
            
            # Call the AI Agent from ai_agent.py
            test_code = generate_passing_test(
                method_name=method.method_name,
                method_source=method_source,
                branch_condition=branch.condition,
                test_file_path=self.temp_test_file, 
                test_name=test_name
            )
            
            # Ensure the generated code is properly indented for the class structure
            indented_code = "\n".join(f"    {line}" for line in test_code.split("\n"))
            generated_tests.append(indented_code)
            
        return "\n\n".join(generated_tests)


def generate_test_code(source_path: str, num_tests: int | None = None) -> str:
    """Main entry point: generate structural test code."""
    from test_generator.code_analyzer import analyze_code
    
    analysis = analyze_code(source_path)
    writer = TestWriter(analysis, num_tests=num_tests)
    return writer.generate_test_file()